name = "chartrequest-microsite-ircs"
type = "javascript"
account_id = "<your-account-id>"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build"
directory = "dist"

[env.production]
route = "<your-production-route>"
zone_id = "<your-zone-id>"
